apiVersion: v1
kind: Service
metadata:
  name: atina-saas
  labels:
    app: atina-saas
spec:
  type: ClusterIP
  selector:
    app: atina-saas
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
