import { randomBytes } from 'crypto';
import { config } from '../../../config';
import { NotFoundError, ValidationError } from '../../../utils/errors';
import logger from '../../../utils/logger';
import { query } from '../../../database/connection';
import { AutonomyBudgetService } from '../../autonomy-loop/service/autonomy-budget.service';
import { catalogBySku, RESOURCE_CATALOG, type ResourceCatalogItem } from '../catalog';
import { ResourceProcurementRepository } from '../repository/resource-procurement.repository';

export type CartLine = { sku: string; qty: number };

function manualPaymentInstructions(reference: string, amountEur: number) {
  const manual = config.payments.manual;
  return {
    reference,
    amountEur,
    currency: manual.currency || 'EUR',
    accountName: manual.accountName || '(popuni MANUAL_PAYMENT_ACCOUNT_NAME)',
    iban: manual.iban || '(popuni MANUAL_PAYMENT_IBAN)',
    bankName: manual.bankName || '(popuni MANUAL_PAYMENT_BANK)',
    swift: manual.swift || '',
    note: `${manual.note} Referenca: ${reference}`,
  };
}

function buildReference(): string {
  const short = randomBytes(4).toString('hex').toUpperCase();
  const prefix = config.payments.manual.referencePrefix || 'OMNI';
  return `${prefix}-RES-${short}`;
}

export class ResourceProcurementService {
  private readonly repo = new ResourceProcurementRepository();
  private readonly budget = new AutonomyBudgetService();

  catalog() {
    return RESOURCE_CATALOG;
  }

  async getSettings() {
    const { rows } = await this.repo.getSettings();
    const raw = (rows[0]?.value ?? {}) as Record<string, unknown>;
    return {
      autoProcurementEnabled: Boolean(raw.autoProcurementEnabled),
    };
  }

  async setAutoProcurement(enabled: boolean) {
    const current = await this.getSettings();
    await this.repo.upsertSettings({
      ...current,
      autoProcurementEnabled: enabled,
    });
    return { autoProcurementEnabled: enabled };
  }

  async walletStatus() {
    const { rows } = await this.repo.listWallets();
    return rows.map((w) => ({
      providerId: w.provider_id,
      balanceEur: parseFloat(w.balance_eur),
      balanceUsd: parseFloat(w.balance_usd),
      lowThresholdEur: parseFloat(w.low_threshold_eur),
      low: parseFloat(w.balance_eur) < parseFloat(w.low_threshold_eur),
    }));
  }

  resolveCart(lines: CartLine[]): { items: Array<ResourceCatalogItem & { qty: number; lineTotalEur: number }>; totalEur: number } {
    if (!lines.length) throw new ValidationError('Korpa je prazna');
    const items: Array<ResourceCatalogItem & { qty: number; lineTotalEur: number }> = [];
    let totalEur = 0;
    for (const line of lines) {
      const qty = Math.max(1, Math.min(10, Math.floor(line.qty || 1)));
      const product = catalogBySku(line.sku.trim());
      if (!product) throw new ValidationError(`Nepoznat proizvod: ${line.sku}`);
      const lineTotalEur = Math.round(product.priceEur * qty * 100) / 100;
      totalEur += lineTotalEur;
      items.push({ ...product, qty, lineTotalEur });
    }
    return { items, totalEur: Math.round(totalEur * 100) / 100 };
  }

  async checkout(userId: string, lines: CartLine[], opts?: { autoGenerated?: boolean }) {
    const { items, totalEur } = this.resolveCart(lines);
    const reference = buildReference();
    const { rows } = await this.repo.createOrder({
      userId,
      totalAmount: totalEur,
      currency: config.payments.manual.currency || 'EUR',
      paymentReference: reference,
      items: items.map((i) => ({
        sku: i.sku,
        qty: i.qty,
        name: i.name,
        providerId: i.providerId,
        lineTotalEur: i.lineTotalEur,
      })),
      autoGenerated: Boolean(opts?.autoGenerated),
    });
    const order = rows[0];
    return {
      order: this.presentOrder(order),
      payment: manualPaymentInstructions(reference, totalEur),
    };
  }

  async listOrders(userId: string) {
    const { rows } = await this.repo.listOrders(userId);
    return rows.map((r) => this.presentOrder(r));
  }

  async markPaid(userId: string, orderId: string) {
    const { rows } = await this.repo.getOrder(orderId);
    const order = rows[0];
    if (!order) throw new NotFoundError('Resource order');
    if (order.user_id !== userId) throw new ValidationError('Order access denied');
    if (order.status !== 'awaiting_payment') {
      throw new ValidationError(`Order status is ${order.status}`);
    }
    const { rows: updated } = await this.repo.updateOrderStatus(orderId, 'paid_pending_confirm');
    logger.info('Resource order marked as paid (pending bank confirm)', { orderId, reference: order.payment_reference });
    return { order: this.presentOrder(updated[0]), pendingConfirm: true };
  }

  async confirmPaid(userId: string, orderId: string) {
    const { rows } = await this.repo.getOrder(orderId);
    const order = rows[0];
    if (!order) throw new NotFoundError('Resource order');
    if (order.user_id !== userId) throw new ValidationError('Order access denied');
    if (order.status !== 'paid_pending_confirm') {
      throw new ValidationError(`Order must be paid_pending_confirm, got ${order.status}`);
    }
    return this.fulfillOrder(orderId, userId);
  }

  async fulfillOrder(orderId: string, userId: string) {
    const { rows } = await this.repo.getOrder(orderId);
    const order = rows[0];
    if (!order) throw new NotFoundError('Resource order');
    if (order.user_id !== userId) throw new ValidationError('Order access denied');
    if (order.status === 'fulfilled') return { order: this.presentOrder(order), alreadyFulfilled: true };
    if (order.status !== 'paid_pending_confirm') {
      throw new ValidationError(`Order cannot be fulfilled from status '${order.status}'`);
    }

    const items = Array.isArray(order.items) ? order.items : JSON.parse(String(order.items || '[]'));
    for (const line of items as Array<{ sku: string; qty: number; providerId?: string }>) {
      const product = catalogBySku(line.sku);
      if (!product) continue;
      const qty = line.qty || 1;
      await this.repo.creditWallet(
        product.providerId,
        product.creditEur * qty,
        product.creditUsd * qty
      );
      await this.budget.creditTopup(product.creditUsd * qty, `resource_${product.providerId}`, {
        metadata: { sku: product.sku, orderId, qty },
      });
    }

    const { rows: updated } = await this.repo.updateOrderStatus(orderId, 'fulfilled', { fulfilledAt: true });
    logger.info('Resource order fulfilled', { orderId, reference: order.payment_reference });
    return { order: this.presentOrder(updated[0]), alreadyFulfilled: false };
  }

  async runAutoProcurement(adminUserId?: string | null): Promise<{ created: boolean; orderId?: string; reason?: string }> {
    const settings = await this.getSettings();
    if (!settings.autoProcurementEnabled) {
      return { created: false, reason: 'auto_disabled' };
    }

    const userId = adminUserId ?? (await this.resolveAdminUserId());
    if (!userId) return { created: false, reason: 'no_admin_user' };

    const wallets = await this.walletStatus();
    const low = wallets.filter((w) => w.low);
    if (!low.length) return { created: false, reason: 'wallets_ok' };

    const target = low.sort((a, b) => a.balanceEur - b.balanceEur)[0];
    const sku =
      target.providerId === 'openrouter'
        ? 'openrouter_10'
        : target.providerId === 'elevenlabs'
          ? 'elevenlabs_10'
          : target.providerId === 'heygen'
            ? 'heygen_starter'
            : target.providerId === 'd-id'
              ? 'did_starter'
              : target.providerId === 'cartesia'
                ? 'cartesia_10'
                : target.providerId === 'comms'
                  ? 'comms_10'
                  : target.providerId === 'apollo'
                    ? 'apollo_25'
                    : target.providerId === 'hunter'
                      ? 'hunter_10'
                      : target.providerId === 'neverbounce' || target.providerId === 'zerobounce'
                        ? 'neverbounce_10'
                        : 'scraper_10';

    const { rows: pending } = await this.repo.listAwaitingPayment(3);
    const duplicate = pending.find((o) => {
      const items = Array.isArray(o.items) ? o.items : JSON.parse(String(o.items || '[]'));
      return (items as Array<{ sku: string }>).some((i) => i.sku === sku);
    });
    if (duplicate) {
      return { created: false, reason: 'pending_order_exists', orderId: duplicate.id };
    }

    const result = await this.checkout(userId, [{ sku, qty: 1 }], { autoGenerated: true });
    return { created: true, orderId: result.order.id, reason: `low_${target.providerId}` };
  }

  private async resolveAdminUserId(): Promise<string | null> {
    const email = config.admin.email.trim();
    if (!email) return null;
    const { rows } = await query<{ id: string }>(
      `SELECT id FROM users WHERE email = $1 AND role IN ('admin', 'superadmin', 'operator') LIMIT 1`,
      [email]
    );
    return rows[0]?.id ?? null;
  }

  private presentOrder(row: {
    id: string;
    status: string;
    currency: string;
    total_amount: string;
    payment_reference: string;
    items: unknown;
    auto_generated: boolean;
    created_at: string;
    fulfilled_at: string | null;
  }) {
    const totalAmount = parseFloat(row.total_amount);
    const base = {
      id: row.id,
      status: row.status,
      currency: row.currency,
      totalAmount,
      paymentReference: row.payment_reference,
      items: row.items,
      autoGenerated: row.auto_generated,
      createdAt: row.created_at,
      fulfilledAt: row.fulfilled_at,
    };
    if (row.status === 'awaiting_payment') {
      return {
        ...base,
        payment: manualPaymentInstructions(row.payment_reference, totalAmount),
      };
    }
    return base;
  }
}
