export type GreenfieldSpec = {
  projectName: string;
  slug: string;
  lane: 'client_order' | 'internal_saas';
  isolationKey: string;
  description: string;
  clientName?: string | null;
};

export function renderPackageJson(spec: GreenfieldSpec): string {
  const pkgName = `@factory/${spec.lane}-${spec.slug}`;
  return `${JSON.stringify(
    {
      name: pkgName,
      version: '0.1.0',
      private: true,
      type: 'module',
      description: spec.description,
      scripts: {
        start: 'node src/index.js',
        test: 'node --test tests/smoke.test.js',
      },
      engines: { node: '>=20' },
      factory: {
        lane: spec.lane,
        isolationKey: spec.isolationKey,
        generatedAt: new Date().toISOString(),
      },
    },
    null,
    2
  )}\n`;
}

export function renderIndexJs(spec: GreenfieldSpec): string {
  return `/**
 * Greenfield app — ${spec.projectName}
 * Lane: ${spec.lane} | Isolation: ${spec.isolationKey}
 */
import http from 'node:http';
import { appMeta } from './config.js';

const PORT = Number(process.env.PORT || 4100);

const server = http.createServer((req, res) => {
  if (req.url === '/health') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: true, ...appMeta }));
    return;
  }
  res.writeHead(200, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ name: appMeta.name, lane: appMeta.lane, isolationKey: appMeta.isolationKey }));
});

server.listen(PORT, () => {
  console.log(\`[\${appMeta.lane}] \${appMeta.name} listening on \${PORT}\`);
});

export { server };
`;
}

export function renderConfigJs(spec: GreenfieldSpec): string {
  return `export const appMeta = ${JSON.stringify(
    {
      name: spec.projectName,
      slug: spec.slug,
      lane: spec.lane,
      isolationKey: spec.isolationKey,
      clientName: spec.clientName ?? null,
      description: spec.description,
    },
    null,
    2
  )};\n`;
}

export function renderSmokeTestJs(spec: GreenfieldSpec): string {
  return `import { test } from 'node:test';
import assert from 'node:assert/strict';
import { appMeta } from '../src/config.js';

test('isolation metadata is present', () => {
  assert.equal(appMeta.lane, '${spec.lane}');
  assert.equal(appMeta.isolationKey, '${spec.isolationKey}');
  assert.equal(appMeta.slug, '${spec.slug}');
});

test('client order lane does not leak internal saas key pattern', () => {
  assert.ok(appMeta.isolationKey.startsWith('${spec.lane === 'client_order' ? 'co-' : 'is-'}'));
});

test('app has name and description', () => {
  assert.ok(appMeta.name.length >= 2);
  assert.ok(appMeta.description.length >= 2);
});
`;
}

export function renderReadme(spec: GreenfieldSpec): string {
  return `# ${spec.projectName}

**Lane:** \`${spec.lane}\`  
**Isolation key:** \`${spec.isolationKey}\`  
${spec.clientName ? `**Client:** ${spec.clientName}\n` : ''}
${spec.description}

## Commands

\`\`\`bash
npm test
npm start
\`\`\`

Generated by Atina Product Factory. Projects in this lane do not share code with other orders.
`;
}

export function renderFactoryMeta(spec: GreenfieldSpec): string {
  return `${JSON.stringify(
    {
      schema: 'product-factory/v1',
      lane: spec.lane,
      isolationKey: spec.isolationKey,
      slug: spec.slug,
      generatedAt: new Date().toISOString(),
      isolated: true,
    },
    null,
    2
  )}\n`;
}
