apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omni-group-staging

resources:
  - ../../base
  - ingress.yaml

namePrefix: staging-

patches:
  - path: patch-replicas.yaml
  - path: patch-env.yaml

images:
  - name: ghcr.io/omni-group/atina-saas
    newName: ghcr.io/omni-group/atina-saas
    newTag: staging
  - name: ghcr.io/omni-group/nest-api
    newTag: staging
  - name: ghcr.io/omni-group/omnigroup-web
    newTag: staging
