/** Sync with atina autonomy-loop/lib/vertical-delivery-profiles.ts marketIntensityDefault */

export const CATEGORY_MARKET_INTENSITY: Record<string, number> = {
  development_it: 62,
  ai_data: 68,
  design_creative: 55,
  writing_translation: 48,
  marketing: 65,
  sales: 70,
  admin_support: 42,
  customer_service: 52,
  business_consulting: 58,
  finance_accounting: 60,
  legal_services: 62,
  ecommerce: 58,
  engineering_architecture: 58,
  video_animation: 54,
  audio_music: 50,
  education_training: 52,
  hr_recruiting: 56,
  photography: 46,
  product_project_management: 60,
  engineering_science: 58,
  web3: 72,
  localization: 50,
  community_moderation: 44,
  creator_services: 52,
  real_estate_services: 58,
  healthcare: 55,
  legal: 62,
  retail: 48,
  hospitality: 44,
  construction: 52,
  education: 52,
  finance: 60,
  logistics: 56,
  beauty: 46,
  fitness: 48,
  agriculture: 50,
  automotive: 54,
  'real-estate': 58,
  manufacturing: 56,
  technology: 64,
  media: 52,
  nonprofit: 40,
  government: 58,
  energy: 62,
  travel: 50,
  professional: 54,
  entertainment: 50,
  home_services: 46,
  pets: 44,
  industrial: 58,
};

export function getCategoryMarketIntensity(categorySlug?: string | null): number {
  if (!categorySlug?.trim()) return 50;
  const key = categorySlug.trim().toLowerCase().replace(/\s+/g, '_');
  return CATEGORY_MARKET_INTENSITY[key] ?? 50;
}

/** Primary deliverable per category — sync with vertical-delivery-profiles primaryDeliverables[0] */
export const CATEGORY_PRIMARY_DELIVERABLE: Record<string, string> = {
  development_it: 'setup-full',
  ai_data: 'integration',
  design_creative: 'landing',
  writing_translation: 'landing',
  marketing: 'lead-gen-retainer',
  sales: 'lead-gen-retainer',
  admin_support: 'setup-quick',
  customer_service: 'ai-support-retainer',
  business_consulting: 'audit',
  finance_accounting: 'audit',
  legal_services: 'audit',
  ecommerce: 'website-ecommerce',
  engineering_architecture: 'audit',
  video_animation: 'landing',
  audio_music: 'landing',
  education_training: 'vertical-package',
  hr_recruiting: 'lead-gen-retainer',
  photography: 'landing',
  product_project_management: 'workflow-design',
  engineering_science: 'audit',
  web3: 'integration',
  localization: 'vertical-package',
  community_moderation: 'vertical-package',
  creator_services: 'landing',
  real_estate_services: 'vertical-package',
  healthcare: 'vertical-package',
  legal: 'audit',
  retail: 'vertical-package',
  hospitality: 'vertical-package',
  construction: 'setup-full',
  education: 'vertical-package',
  finance: 'audit',
  logistics: 'vertical-package',
  beauty: 'vertical-package',
  fitness: 'vertical-package',
  agriculture: 'vertical-package',
  automotive: 'vertical-package',
  'real-estate': 'vertical-package',
  manufacturing: 'setup-full',
  technology: 'setup-full',
  media: 'landing',
  nonprofit: 'setup-quick',
  government: 'audit',
  energy: 'audit',
  travel: 'vertical-package',
  professional: 'audit',
  entertainment: 'landing',
  home_services: 'vertical-package',
  pets: 'vertical-package',
  industrial: 'setup-full',
};

export function getCategoryPrimaryDeliverable(categorySlug: string): string {
  const key = categorySlug.trim().toLowerCase().replace(/\s+/g, '_');
  return CATEGORY_PRIMARY_DELIVERABLE[key] ?? 'vertical-package';
}
