import { query } from '../../../database/connection';

export type ProcurementOrderRow = {
  id: string;
  user_id: string;
  status: string;
  currency: string;
  total_amount: string;
  payment_reference: string;
  items: unknown;
  auto_generated: boolean;
  metadata: unknown;
  created_at: string;
  updated_at: string;
  fulfilled_at: string | null;
};

export type ProviderWalletRow = {
  provider_id: string;
  balance_eur: string;
  balance_usd: string;
  low_threshold_eur: string;
  metadata: unknown;
  updated_at: string;
};

export class ResourceProcurementRepository {
  getSettings() {
    return query<{ key: string; value: unknown }>(
      `SELECT key, value FROM platform_settings WHERE key = 'resource_procurement'`
    );
  }

  upsertSettings(value: Record<string, unknown>) {
    return query(
      `INSERT INTO platform_settings (key, value, updated_at)
       VALUES ('resource_procurement', $1, NOW())
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()`,
      [JSON.stringify(value)]
    );
  }

  createOrder(input: {
    userId: string;
    totalAmount: number;
    currency: string;
    paymentReference: string;
    items: unknown[];
    autoGenerated: boolean;
    metadata?: Record<string, unknown>;
  }) {
    return query<ProcurementOrderRow>(
      `INSERT INTO resource_procurement_orders
         (user_id, status, currency, total_amount, payment_reference, items, auto_generated, metadata)
       VALUES ($1, 'awaiting_payment', $2, $3, $4, $5, $6, $7)
       RETURNING *`,
      [
        input.userId,
        input.currency,
        input.totalAmount,
        input.paymentReference,
        JSON.stringify(input.items),
        input.autoGenerated,
        JSON.stringify(input.metadata ?? {}),
      ]
    );
  }

  getOrder(id: string) {
    return query<ProcurementOrderRow>(
      `SELECT * FROM resource_procurement_orders WHERE id = $1`,
      [id]
    );
  }

  listOrders(userId: string, limit = 20) {
    return query<ProcurementOrderRow>(
      `SELECT * FROM resource_procurement_orders
       WHERE user_id = $1
       ORDER BY created_at DESC
       LIMIT $2`,
      [userId, limit]
    );
  }

  listAwaitingPayment(limit = 10) {
    return query<ProcurementOrderRow>(
      `SELECT * FROM resource_procurement_orders
       WHERE status IN ('awaiting_payment', 'paid_pending_confirm')
       ORDER BY created_at ASC
       LIMIT $1`,
      [limit]
    );
  }

  updateOrderStatus(id: string, status: string, extra?: { fulfilledAt?: boolean }) {
    const fulfilled = extra?.fulfilledAt ? ', fulfilled_at = NOW()' : '';
    return query<ProcurementOrderRow>(
      `UPDATE resource_procurement_orders
       SET status = $2, updated_at = NOW()${fulfilled}
       WHERE id = $1
       RETURNING *`,
      [id, status]
    );
  }

  listWallets() {
    return query<ProviderWalletRow>(
      `SELECT * FROM resource_provider_wallets ORDER BY provider_id ASC`
    );
  }

  creditWallet(providerId: string, creditEur: number, creditUsd: number) {
    return query<ProviderWalletRow>(
      `UPDATE resource_provider_wallets
       SET balance_eur = balance_eur + $2,
           balance_usd = balance_usd + $3,
           updated_at = NOW()
       WHERE provider_id = $1
       RETURNING *`,
      [providerId, creditEur, creditUsd]
    );
  }

  getWallet(providerId: string) {
    return query<ProviderWalletRow>(
      `SELECT * FROM resource_provider_wallets WHERE provider_id = $1`,
      [providerId]
    );
  }
}
