'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Loader2, Power, RefreshCw, ShoppingCart, Wallet } from 'lucide-react';

type CatalogItem = {
  sku: string;
  providerId: string;
  name: string;
  description: string;
  priceEur: number;
  category: string;
};

type WalletRow = {
  providerId: string;
  balanceEur: number;
  lowThresholdEur: number;
  low: boolean;
};

type OrderRow = {
  id: string;
  status: string;
  totalAmount: number;
  paymentReference: string;
  items: Array<{ sku: string; name: string; qty: number; lineTotalEur: number }>;
  autoGenerated: boolean;
  createdAt: string;
  fulfilledAt: string | null;
};

type PaymentInfo = {
  reference: string;
  amountEur: number;
  currency: string;
  accountName: string;
  iban: string;
  bankName: string;
  note: string;
};

type Props = {
  disabled?: boolean;
};

export function ResourceShopPanel({ disabled }: Props) {
  const [catalog, setCatalog] = useState<CatalogItem[]>([]);
  const [cart, setCart] = useState<Record<string, number>>({});
  const [wallets, setWallets] = useState<WalletRow[]>([]);
  const [orders, setOrders] = useState<OrderRow[]>([]);
  const [autoOn, setAutoOn] = useState(false);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);
  const [payment, setPayment] = useState<PaymentInfo | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);

  const cartTotal = useMemo(() => {
    return catalog.reduce((sum, item) => {
      const qty = cart[item.sku] ?? 0;
      return sum + item.priceEur * qty;
    }, 0);
  }, [catalog, cart]);

  const cartLines = useMemo(
    () =>
      Object.entries(cart)
        .filter(([, qty]) => qty > 0)
        .map(([sku, qty]) => ({ sku, qty })),
    [cart]
  );

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const [catRes, setRes, ordRes] = await Promise.all([
        fetch('/api/atina/resource-procurement/catalog'),
        fetch('/api/atina/resource-procurement/settings'),
        fetch('/api/atina/resource-procurement/orders'),
      ]);
      const catJson = (await catRes.json()) as { ok?: boolean; data?: { items?: CatalogItem[] } };
      const setJson = (await setRes.json()) as {
        ok?: boolean;
        data?: { settings?: { autoProcurementEnabled?: boolean }; wallets?: WalletRow[] };
      };
      const ordJson = (await ordRes.json()) as { ok?: boolean; data?: { orders?: OrderRow[] } };
      if (catRes.ok && catJson.ok) {
        setCatalog(catJson.data?.items ?? []);
      } else {
        setError('Resource catalog unavailable — check the Atina API.');
      }
      if (setRes.ok && setJson.ok && setJson.data) {
        setAutoOn(Boolean(setJson.data.settings?.autoProcurementEnabled));
        setWallets(setJson.data.wallets ?? []);
      }
      if (ordRes.ok && ordJson.ok) setOrders(ordJson.data?.orders ?? []);
    } catch {
      setError('Unable to load the resource shop.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!disabled) void load();
  }, [disabled, load]);

  const toggleAuto = async () => {
    setBusy('auto');
    setError(null);
    try {
      const res = await fetch('/api/atina/resource-procurement/settings/auto', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ enabled: !autoOn }),
      });
      const body = (await res.json()) as { ok?: boolean; data?: { autoProcurementEnabled?: boolean } };
      if (!body.ok) throw new Error('toggle_failed');
      setAutoOn(Boolean(body.data?.autoProcurementEnabled));
      setMessage(!autoOn ? 'Auto-procurement enabled.' : 'Auto-procurement disabled.');
    } catch {
      setError('Auto-procurement toggle failed.');
    } finally {
      setBusy(null);
    }
  };

  const checkout = async () => {
    if (!cartLines.length) return;
    setBusy('checkout');
    setError(null);
    setMessage(null);
    setPayment(null);
    try {
      const res = await fetch('/api/atina/resource-procurement/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ items: cartLines }),
      });
      const body = (await res.json()) as {
        ok?: boolean;
        data?: { payment?: PaymentInfo; order?: OrderRow };
        detail?: string;
      };
      if (!body.ok) throw new Error(body.detail ?? 'checkout_failed');
      setPayment(body.data?.payment ?? null);
      setCart({});
      setMessage('Order created. Pay using the reference below, then click "I have confirmed payment".');
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Checkout failed');
    } finally {
      setBusy(null);
    }
  };

  const markPaid = async (orderId: string) => {
    setBusy(orderId);
    setError(null);
    try {
      const res = await fetch(`/api/atina/resource-procurement/orders/${orderId}/mark-paid`, {
        method: 'POST',
      });
      const body = (await res.json()) as { ok?: boolean; detail?: string };
      if (!body.ok) throw new Error(body.detail ?? 'mark_paid_failed');
      setPayment(null);
      setMessage('Resources activated in the system — no need to log into provider sites.');
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Payment confirmation failed');
    } finally {
      setBusy(null);
    }
  };

  const addToCart = (sku: string) => {
    setCart((prev) => ({ ...prev, [sku]: Math.min(10, (prev[sku] ?? 0) + 1) }));
  };

  if (disabled) {
    return (
      <p className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-100">
        Sign in with an admin account to purchase API resources through the system.
      </p>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <button
            type="button"
            disabled={busy === 'auto'}
            onClick={() => void toggleAuto()}
            className={`flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-medium transition ${
              autoOn
                ? 'border-emerald-500/40 bg-emerald-500/15 text-emerald-100'
                : 'border-white/10 bg-white/[0.03] text-slate-300'
            }`}
          >
            <Power className="h-4 w-4" />
            Auto-procurement: {autoOn ? 'ON' : 'OFF'}
          </button>
          <p className="text-xs text-slate-500">
            When ON, the system creates an order when resources fall below the threshold.
          </p>
        </div>
        <button type="button" className="btn-ghost text-violet-300" onClick={() => void load()}>
          {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
        </button>
      </div>

      {message && <p className="text-sm text-emerald-300">{message}</p>}
      {error && <p className="text-sm text-rose-400">{error}</p>}

      {payment && (
        <div className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 p-4 text-sm text-cyan-50">
          <p className="font-medium">Payment instructions</p>
          <p className="mt-2">Amount: {payment.amountEur} {payment.currency}</p>
          <p>Reference: <span className="font-mono">{payment.reference}</span></p>
          <p>Beneficiary: {payment.accountName}</p>
          <p>IBAN: <span className="font-mono">{payment.iban}</span></p>
          <p>Bank: {payment.bankName}</p>
          <p className="mt-2 text-xs text-cyan-200/80">{payment.note}</p>
        </div>
      )}

      <div className="grid gap-4 lg:grid-cols-2">
        <div>
          <h3 className="mb-2 flex items-center gap-2 text-sm font-semibold text-white">
            <ShoppingCart className="h-4 w-4 text-violet-400" /> Resource cart
          </h3>
          <div className="space-y-2">
            {loading && catalog.length === 0 && (
              <p className="flex items-center gap-2 text-xs text-slate-500">
                <Loader2 className="h-3.5 w-3.5 animate-spin" /> Loading catalog…
              </p>
            )}
            {!loading && catalog.length === 0 && (
              <p className="text-xs text-slate-500">
                No resource SKUs available right now.
              </p>
            )}
            {catalog.map((item) => (
              <div
                key={item.sku}
                className="flex items-start justify-between gap-3 rounded-xl border border-white/10 bg-white/[0.02] p-3"
              >
                <div>
                  <p className="font-medium text-white">{item.name}</p>
                  <p className="text-xs text-slate-400">{item.description}</p>
                  <p className="mt-1 text-xs text-violet-300">
                    €{item.priceEur} · {item.providerId}
                    {(cart[item.sku] ?? 0) > 0 ? ` · x${cart[item.sku]}` : ''}
                  </p>
                </div>
                <button type="button" className="btn-glass text-xs" onClick={() => addToCart(item.sku)}>
                  Add
                </button>
              </div>
            ))}
          </div>
          <div className="mt-3 flex items-center justify-between">
            <p className="text-sm text-slate-300">Total: €{cartTotal.toFixed(2)}</p>
            <button
              type="button"
              disabled={!cartLines.length || busy === 'checkout'}
              className="btn-primary text-sm disabled:opacity-50"
              onClick={() => void checkout()}
            >
              {busy === 'checkout' ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Place order & pay'}
            </button>
          </div>
        </div>

        <div>
          <h3 className="mb-2 flex items-center gap-2 text-sm font-semibold text-white">
            <Wallet className="h-4 w-4 text-cyan-400" /> Provider balances
          </h3>
          <div className="space-y-2">
            {wallets.map((w) => (
              <div
                key={w.providerId}
                className={`rounded-xl border p-3 text-sm ${
                  w.low ? 'border-amber-500/30 bg-amber-500/10' : 'border-white/10 bg-white/[0.02]'
                }`}
              >
                <p className="font-medium text-white">{w.providerId}</p>
                <p className="text-slate-400">
                  €{w.balanceEur.toFixed(2)} · threshold €{w.lowThresholdEur}
                  {w.low ? ' · low' : ''}
                </p>
              </div>
            ))}
          </div>

          <h3 className="mb-2 mt-4 text-sm font-semibold text-white">Orders</h3>
          {orders.length === 0 ? (
            <p className="text-xs text-slate-500">No orders yet.</p>
          ) : (
            <ul className="space-y-2">
              {orders.slice(0, 6).map((o) => (
                <li key={o.id} className="rounded-xl border border-white/10 p-3 text-xs">
                  <p className="font-mono text-violet-300">{o.paymentReference}</p>
                  <p className="text-slate-400">
                    €{o.totalAmount} · {o.status}
                    {o.autoGenerated ? ' · auto' : ''}
                  </p>
                  {o.status === 'awaiting_payment' && (
                    <button
                      type="button"
                      disabled={busy === o.id}
                      className="mt-2 btn-glass text-xs"
                      onClick={() => void markPaid(o.id)}
                    >
                      {busy === o.id ? '...' : 'I have confirmed payment'}
                    </button>
                  )}
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>
    </div>
  );
}
