apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omni-group-prod

resources:
  - ../../base
  - ingress.yaml
  - hpa-atina.yaml

namePrefix: prod-

patches:
  - path: patch-replicas.yaml
  - path: patch-env.yaml

images:
  - name: ghcr.io/omni-group/atina-saas
    newTag: prod
  - name: ghcr.io/omni-group/nest-api
    newTag: prod
  - name: ghcr.io/omni-group/omnigroup-web
    newTag: prod
