import PDFDocument from 'pdfkit';

export type DeliverablePdfSection = {
  heading: string;
  body: string;
};

export type DeliverablePdfInput = {
  brandName: string;
  title: string;
  subtitle?: string;
  clientName: string;
  deliverableName: string;
  sections: DeliverablePdfSection[];
  footerNote?: string;
};

export function generateDeliverablePdfBuffer(input: DeliverablePdfInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(18).fillColor('#1e1b4b').text(input.brandName);
    doc.moveDown(0.3);
    doc.fontSize(14).fillColor('#000').text(input.title, { underline: true });
    if (input.subtitle) {
      doc.fontSize(10).fillColor('#555').text(input.subtitle);
    }
    doc.moveDown();
    doc.fontSize(10).fillColor('#333')
      .text(`Prepared for: ${input.clientName}`)
      .text(`Deliverable: ${input.deliverableName}`)
      .text(`Date: ${new Date().toLocaleDateString('en-GB')}`);
    doc.moveDown();

    for (const section of input.sections) {
      doc.fontSize(12).fillColor('#1e1b4b').text(section.heading, { underline: true });
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor('#222').text(section.body, { align: 'left', lineGap: 3 });
      doc.moveDown();
    }

    doc.moveDown();
    doc.fontSize(8).fillColor('#666').text(
      input.footerNote ??
        'This document was generated by Omni Group automated delivery. Review with your team before production use.',
      { align: 'center' },
    );

    doc.end();
  });
}
