import PDFDocument from 'pdfkit';

export type DeliverablePdfSection = {
  heading: string;
  body: string;
};

export type DeliverablePdfInput = {
  brandName: string;
  title: string;
  subtitle?: string;
  clientName: string;
  deliverableName: string;
  sections: DeliverablePdfSection[];
  footerNote?: string;
};

export type DeliverablePdfResult = {
  buffer: Buffer;
  pageCount: number;
  byteLength: number;
};

/**
 * Render a multi-page A4 PDF from structured sections.
 * Page breaks are automatic; footers include page numbers for client handoff.
 */
export function generateDeliverablePdf(input: DeliverablePdfInput): Promise<DeliverablePdfResult> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true, autoFirstPage: true });
    const chunks: Buffer[] = [];
    let pageCount = 1;
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('error', reject);
    doc.on('end', () => {
      const buffer = Buffer.concat(chunks);
      resolve({
        buffer,
        pageCount,
        byteLength: buffer.byteLength,
      });
    });

    const footerNote =
      input.footerNote ??
      'This document was generated by Omni Group automated delivery. Review with your team before production use.';

    doc.fontSize(18).fillColor('#1e1b4b').text(input.brandName);
    doc.moveDown(0.3);
    doc.fontSize(14).fillColor('#000').text(input.title, { underline: true });
    if (input.subtitle) {
      doc.fontSize(10).fillColor('#555').text(input.subtitle);
    }
    doc.moveDown();
    doc
      .fontSize(10)
      .fillColor('#333')
      .text(`Prepared for: ${input.clientName}`)
      .text(`Deliverable: ${input.deliverableName}`)
      .text(`Date: ${new Date().toLocaleDateString('en-GB')}`);
    doc.moveDown();

    for (const section of input.sections) {
      doc.fontSize(12).fillColor('#1e1b4b').text(section.heading, { underline: true });
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor('#222').text(section.body, { align: 'left', lineGap: 3 });
      doc.moveDown();
    }

    // Capture page count before end() — bufferedPageRange is empty after flush.
    const range = doc.bufferedPageRange();
    pageCount = Math.max(1, range.count);
    for (let i = 0; i < range.count; i += 1) {
      doc.switchToPage(range.start + i);
      const bottom = doc.page.height - 40;
      doc
        .fontSize(8)
        .fillColor('#666')
        .text(footerNote, 50, bottom - 12, {
          width: doc.page.width - 100,
          align: 'left',
          lineBreak: false,
        });
      doc.text(`Page ${i + 1} of ${pageCount}`, 50, bottom, {
        width: doc.page.width - 100,
        align: 'right',
        lineBreak: false,
      });
    }

    doc.end();
  });
}

/** Back-compat wrapper — prefer generateDeliverablePdf when page/byte metrics are needed. */
export function generateDeliverablePdfBuffer(input: DeliverablePdfInput): Promise<Buffer> {
  return generateDeliverablePdf(input).then((r) => r.buffer);
}
